### ISSUE TITLE
server side rendering does not allow socket.io-client

### ISSUE THREAD

**Issue by Simba167657** [DCtheTall/node-video-chat#10]
Please tell me about installing app.

I have installed app.
But when I was starting the app , there were some errors.

PS C:\Users\Developer\Documents\node-video-chat> nodemon start
[nodemon] 2.0.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node start build/start.js`
### **server side rendering does not allow socket.io-client**
Listening on port 4000
Executing (default): SELECT 1+1 AS result
Connected to PostgreSQL database

**Comment by Simba167657** [comment]
> Please tell me about installing app.
> 
> I have installed all npm packages.
> But when I was starting the app , there were some errors.
> There wasn't 'C:\Users\Developer\Documents\node-video-chat\build' folder in directory.
> Here.
> 
> PS C:\Users\Developer\Documents\node-video-chat> npm start
> 
> > node-video-chat@1.0.0 start C:\Users\Developer\Documents\node-video-chat
> > node build/start
> 
> internal/modules/cjs/loader.js:985
> throw err;
> ^
> 
> Error: Cannot find module 'C:\Users\Developer\Documents\node-video-chat\build\start'
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
> at Function.Module._load (internal/modules/cjs/loader.js:864:27)
> at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
> at internal/main/run_main_module.js:18:47 {
> code: 'MODULE_NOT_FOUND',
> requireStack: []
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-video-chat@1.0.0 start: `node build/start`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-video-chat@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Developer\AppData\Roaming\npm-cache_logs\2020-04-22T09_46_31_388Z-debug.log

**Comment by DCtheTall** [comment]
This message is expected. You cannot use socket.io-client on Node.js since it relies on APIs only available in the DOM.

When we build the client-side code for SSR, we need to detect if these DOMs are available and have a dynamic import conditionally load the socket.io-client model. I added the console message just to confirm my method was working as I was building it, if it is confusing then I can remove it, or if you want to supply a PR you are welcome.
