### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PareshSolankiMI** [DCtheTall/node-video-chat#15]
When I run graphql server and hit / request then i got bellow error. Can you please help me on it?

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: GraphQL error: WHERE parameter "id" has invalid "undefined" value

**Comment by DCtheTall** [comment]
Please provide more information. What exactly are you trying to do with the app that's leading to this error? Are you sure your environmental variables are all set up properly?
