### ISSUE TITLE
The demo isn't working

### ISSUE THREAD

**Issue by zefexdeveloper** [DCtheTall/node-video-chat#20]
For some reason the demo isn't working, when you call another person and the message to accept appears it never connects. It says: it wasn't able to reach.

**Comment by DCtheTall** [comment]
Twilio suspended my account due to lack of funds 😆 

I am paying the balance now so it should start working again soon.

**Comment by zefexdeveloper** [comment]
@DCtheTall I never used Twilio, I thought they had a free account for development usage with some kind of daily usage limit.
